[package]
name = "bos_pkg"
version = "0.1.0"
authors = ["bubbyroosh <bubbyroosh@firemail.cc>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rargsxd = "0.1.5"
sudo = "0.6.0"
yaml-rust = "0.4"
git2 = "0.13"
