name: vim
description: A text editor?? lol
depends:
  - libs/ncurses

files:
  - /usr/local/bin/vim
  - /usr/local/share/vim
  - /usr/local/share/man/man1/vimdiff.1
  - /usr/local/share/man/man1/vimtutor.1

git: https://github.com/vim/vim
